name: Run trend checker

on:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-trend-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter Trend Scraper
        run: python twitterTrendsScraperV2.py
      - name: Run DDG Search
        run: |    
          python ddg_trends_US.py
          python ddg_trends_UK.py
      - name: Run Google Search
        run: |    
          python uk_trends_to_google_results_keyed_ratelimit.py ${{ secrets.UK_GOOGLE_API_KEY}}
          python us_trends_to_google_results_keyed_ratelimit.py ${{ secrets.US_GOOGLE_API_KEY}}
          python ru_trends_to_google_results_keyed_ratelimit.py ${{ secrets.RU_GOOGLE_API_KEY}}
      - name: Run VirusTotal Check
        run: |    
          python virus_total_check_CSVinput_V2.py ${{ secrets.ACADEMIC_API_KEY }}

      - name: Commit and push all changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          current_date=$(date +"%m/%d/%Y")
          git add .
          git commit -m "Trends for day $current_date"
          git push